// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v7.34.0
// source: QueueHandler.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type ClientWritableStream,
  type handleClientStreamingCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "";

export interface StreamMetricRequest {
  targetID: string;
}

export interface StreamMetricResponse {
  metric: MetricResponse[];
}

export interface LoadMetricRequest {
  data: MetricResponse | undefined;
}

export interface LoadMetricResponse {
  message: string;
}

export interface GetMetricRequest {
  targetID: string;
}

export interface GetMetricResponse {
  metric: MetricResponse[];
}

export interface RawMetrics {
  cpu: number;
  memory: number;
  latency: number;
  failedReq: number;
  failedLogins: number;
  totalReq: number;
  totalLogins: number;
}

export interface MetricResponse {
  timestamp: string;
  data: RawMetrics | undefined;
}

function createBaseStreamMetricRequest(): StreamMetricRequest {
  return { targetID: "" };
}

export const StreamMetricRequest: MessageFns<StreamMetricRequest> = {
  encode(message: StreamMetricRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.targetID !== "") {
      writer.uint32(10).string(message.targetID);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamMetricRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamMetricRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.targetID = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StreamMetricRequest {
    return { targetID: isSet(object.targetID) ? globalThis.String(object.targetID) : "" };
  },

  toJSON(message: StreamMetricRequest): unknown {
    const obj: any = {};
    if (message.targetID !== "") {
      obj.targetID = message.targetID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamMetricRequest>, I>>(base?: I): StreamMetricRequest {
    return StreamMetricRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamMetricRequest>, I>>(object: I): StreamMetricRequest {
    const message = createBaseStreamMetricRequest();
    message.targetID = object.targetID ?? "";
    return message;
  },
};

function createBaseStreamMetricResponse(): StreamMetricResponse {
  return { metric: [] };
}

export const StreamMetricResponse: MessageFns<StreamMetricResponse> = {
  encode(message: StreamMetricResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.metric) {
      MetricResponse.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamMetricResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamMetricResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.metric.push(MetricResponse.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StreamMetricResponse {
    return {
      metric: globalThis.Array.isArray(object?.metric) ? object.metric.map((e: any) => MetricResponse.fromJSON(e)) : [],
    };
  },

  toJSON(message: StreamMetricResponse): unknown {
    const obj: any = {};
    if (message.metric?.length) {
      obj.metric = message.metric.map((e) => MetricResponse.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamMetricResponse>, I>>(base?: I): StreamMetricResponse {
    return StreamMetricResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamMetricResponse>, I>>(object: I): StreamMetricResponse {
    const message = createBaseStreamMetricResponse();
    message.metric = object.metric?.map((e) => MetricResponse.fromPartial(e)) || [];
    return message;
  },
};

function createBaseLoadMetricRequest(): LoadMetricRequest {
  return { data: undefined };
}

export const LoadMetricRequest: MessageFns<LoadMetricRequest> = {
  encode(message: LoadMetricRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      MetricResponse.encode(message.data, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoadMetricRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoadMetricRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = MetricResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoadMetricRequest {
    return { data: isSet(object.data) ? MetricResponse.fromJSON(object.data) : undefined };
  },

  toJSON(message: LoadMetricRequest): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = MetricResponse.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoadMetricRequest>, I>>(base?: I): LoadMetricRequest {
    return LoadMetricRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoadMetricRequest>, I>>(object: I): LoadMetricRequest {
    const message = createBaseLoadMetricRequest();
    message.data = (object.data !== undefined && object.data !== null)
      ? MetricResponse.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseLoadMetricResponse(): LoadMetricResponse {
  return { message: "" };
}

export const LoadMetricResponse: MessageFns<LoadMetricResponse> = {
  encode(message: LoadMetricResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoadMetricResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoadMetricResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoadMetricResponse {
    return { message: isSet(object.message) ? globalThis.String(object.message) : "" };
  },

  toJSON(message: LoadMetricResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoadMetricResponse>, I>>(base?: I): LoadMetricResponse {
    return LoadMetricResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoadMetricResponse>, I>>(object: I): LoadMetricResponse {
    const message = createBaseLoadMetricResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseGetMetricRequest(): GetMetricRequest {
  return { targetID: "" };
}

export const GetMetricRequest: MessageFns<GetMetricRequest> = {
  encode(message: GetMetricRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.targetID !== "") {
      writer.uint32(10).string(message.targetID);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMetricRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMetricRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.targetID = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetMetricRequest {
    return { targetID: isSet(object.targetID) ? globalThis.String(object.targetID) : "" };
  },

  toJSON(message: GetMetricRequest): unknown {
    const obj: any = {};
    if (message.targetID !== "") {
      obj.targetID = message.targetID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMetricRequest>, I>>(base?: I): GetMetricRequest {
    return GetMetricRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMetricRequest>, I>>(object: I): GetMetricRequest {
    const message = createBaseGetMetricRequest();
    message.targetID = object.targetID ?? "";
    return message;
  },
};

function createBaseGetMetricResponse(): GetMetricResponse {
  return { metric: [] };
}

export const GetMetricResponse: MessageFns<GetMetricResponse> = {
  encode(message: GetMetricResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.metric) {
      MetricResponse.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMetricResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMetricResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.metric.push(MetricResponse.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetMetricResponse {
    return {
      metric: globalThis.Array.isArray(object?.metric) ? object.metric.map((e: any) => MetricResponse.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetMetricResponse): unknown {
    const obj: any = {};
    if (message.metric?.length) {
      obj.metric = message.metric.map((e) => MetricResponse.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMetricResponse>, I>>(base?: I): GetMetricResponse {
    return GetMetricResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMetricResponse>, I>>(object: I): GetMetricResponse {
    const message = createBaseGetMetricResponse();
    message.metric = object.metric?.map((e) => MetricResponse.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRawMetrics(): RawMetrics {
  return { cpu: 0, memory: 0, latency: 0, failedReq: 0, failedLogins: 0, totalReq: 0, totalLogins: 0 };
}

export const RawMetrics: MessageFns<RawMetrics> = {
  encode(message: RawMetrics, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cpu !== 0) {
      writer.uint32(9).double(message.cpu);
    }
    if (message.memory !== 0) {
      writer.uint32(17).double(message.memory);
    }
    if (message.latency !== 0) {
      writer.uint32(25).double(message.latency);
    }
    if (message.failedReq !== 0) {
      writer.uint32(32).int32(message.failedReq);
    }
    if (message.failedLogins !== 0) {
      writer.uint32(40).int32(message.failedLogins);
    }
    if (message.totalReq !== 0) {
      writer.uint32(48).int32(message.totalReq);
    }
    if (message.totalLogins !== 0) {
      writer.uint32(56).int32(message.totalLogins);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RawMetrics {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRawMetrics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.cpu = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.memory = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.latency = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.failedReq = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.failedLogins = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.totalReq = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.totalLogins = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RawMetrics {
    return {
      cpu: isSet(object.cpu) ? globalThis.Number(object.cpu) : 0,
      memory: isSet(object.memory) ? globalThis.Number(object.memory) : 0,
      latency: isSet(object.latency) ? globalThis.Number(object.latency) : 0,
      failedReq: isSet(object.failedReq)
        ? globalThis.Number(object.failedReq)
        : isSet(object.failed_req)
        ? globalThis.Number(object.failed_req)
        : 0,
      failedLogins: isSet(object.failedLogins)
        ? globalThis.Number(object.failedLogins)
        : isSet(object.failed_logins)
        ? globalThis.Number(object.failed_logins)
        : 0,
      totalReq: isSet(object.totalReq)
        ? globalThis.Number(object.totalReq)
        : isSet(object.total_req)
        ? globalThis.Number(object.total_req)
        : 0,
      totalLogins: isSet(object.totalLogins)
        ? globalThis.Number(object.totalLogins)
        : isSet(object.total_logins)
        ? globalThis.Number(object.total_logins)
        : 0,
    };
  },

  toJSON(message: RawMetrics): unknown {
    const obj: any = {};
    if (message.cpu !== 0) {
      obj.cpu = message.cpu;
    }
    if (message.memory !== 0) {
      obj.memory = message.memory;
    }
    if (message.latency !== 0) {
      obj.latency = message.latency;
    }
    if (message.failedReq !== 0) {
      obj.failedReq = Math.round(message.failedReq);
    }
    if (message.failedLogins !== 0) {
      obj.failedLogins = Math.round(message.failedLogins);
    }
    if (message.totalReq !== 0) {
      obj.totalReq = Math.round(message.totalReq);
    }
    if (message.totalLogins !== 0) {
      obj.totalLogins = Math.round(message.totalLogins);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RawMetrics>, I>>(base?: I): RawMetrics {
    return RawMetrics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RawMetrics>, I>>(object: I): RawMetrics {
    const message = createBaseRawMetrics();
    message.cpu = object.cpu ?? 0;
    message.memory = object.memory ?? 0;
    message.latency = object.latency ?? 0;
    message.failedReq = object.failedReq ?? 0;
    message.failedLogins = object.failedLogins ?? 0;
    message.totalReq = object.totalReq ?? 0;
    message.totalLogins = object.totalLogins ?? 0;
    return message;
  },
};

function createBaseMetricResponse(): MetricResponse {
  return { timestamp: "", data: undefined };
}

export const MetricResponse: MessageFns<MetricResponse> = {
  encode(message: MetricResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== "") {
      writer.uint32(10).string(message.timestamp);
    }
    if (message.data !== undefined) {
      RawMetrics.encode(message.data, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MetricResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMetricResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = RawMetrics.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MetricResponse {
    return {
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
      data: isSet(object.data) ? RawMetrics.fromJSON(object.data) : undefined,
    };
  },

  toJSON(message: MetricResponse): unknown {
    const obj: any = {};
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    if (message.data !== undefined) {
      obj.data = RawMetrics.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MetricResponse>, I>>(base?: I): MetricResponse {
    return MetricResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MetricResponse>, I>>(object: I): MetricResponse {
    const message = createBaseMetricResponse();
    message.timestamp = object.timestamp ?? "";
    message.data = (object.data !== undefined && object.data !== null)
      ? RawMetrics.fromPartial(object.data)
      : undefined;
    return message;
  },
};

export type QueueService = typeof QueueService;
export const QueueService = {
  loadMetric: {
    path: "/Queue/LoadMetric",
    requestStream: true,
    responseStream: false,
    requestSerialize: (value: LoadMetricRequest): Buffer => Buffer.from(LoadMetricRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): LoadMetricRequest => LoadMetricRequest.decode(value),
    responseSerialize: (value: LoadMetricResponse): Buffer => Buffer.from(LoadMetricResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): LoadMetricResponse => LoadMetricResponse.decode(value),
  },
  getMetric: {
    path: "/Queue/GetMetric",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetMetricRequest): Buffer => Buffer.from(GetMetricRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetMetricRequest => GetMetricRequest.decode(value),
    responseSerialize: (value: GetMetricResponse): Buffer => Buffer.from(GetMetricResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetMetricResponse => GetMetricResponse.decode(value),
  },
  streamMetrics: {
    path: "/Queue/StreamMetrics",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: StreamMetricRequest): Buffer => Buffer.from(StreamMetricRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): StreamMetricRequest => StreamMetricRequest.decode(value),
    responseSerialize: (value: StreamMetricResponse): Buffer =>
      Buffer.from(StreamMetricResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): StreamMetricResponse => StreamMetricResponse.decode(value),
  },
} as const;

export interface QueueServer extends UntypedServiceImplementation {
  loadMetric: handleClientStreamingCall<LoadMetricRequest, LoadMetricResponse>;
  getMetric: handleUnaryCall<GetMetricRequest, GetMetricResponse>;
  streamMetrics: handleServerStreamingCall<StreamMetricRequest, StreamMetricResponse>;
}

export interface QueueClient extends Client {
  loadMetric(
    callback: (error: ServiceError | null, response: LoadMetricResponse) => void,
  ): ClientWritableStream<LoadMetricRequest>;
  loadMetric(
    metadata: Metadata,
    callback: (error: ServiceError | null, response: LoadMetricResponse) => void,
  ): ClientWritableStream<LoadMetricRequest>;
  loadMetric(
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: LoadMetricResponse) => void,
  ): ClientWritableStream<LoadMetricRequest>;
  loadMetric(
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: LoadMetricResponse) => void,
  ): ClientWritableStream<LoadMetricRequest>;
  getMetric(
    request: GetMetricRequest,
    callback: (error: ServiceError | null, response: GetMetricResponse) => void,
  ): ClientUnaryCall;
  getMetric(
    request: GetMetricRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetMetricResponse) => void,
  ): ClientUnaryCall;
  getMetric(
    request: GetMetricRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetMetricResponse) => void,
  ): ClientUnaryCall;
  streamMetrics(
    request: StreamMetricRequest,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<StreamMetricResponse>;
  streamMetrics(
    request: StreamMetricRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<StreamMetricResponse>;
}

export const QueueClient = makeGenericClientConstructor(QueueService, "Queue") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): QueueClient;
  service: typeof QueueService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
